force-app/main/default/objects/Pizza__mdt/Pizza__mdt.object-meta.xml
<CustomObject>
    <description>Used in our reflective pizza factory</description>
    <label>Pizza</label>
    <pluralLabel>Pizzas</pluralLabel>
</CustomObject>

force-app/main/default/objects/Pizza__mdt/fields/Class_To_Instantiate__c.field-meta.xml
<CustomField>
    <fullName>Class_To_Instantiate__c</fullName>
    <description>Name of the object that our factory will return an instance of.</description>
    <label>Class To Instantiate</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ReflectiveFactory/ReflectivePizzaFactory.cls
/**
 * Instead of updating our factory every time we need to add a concrete pizza we simple add a value to custom metadata
 * and let the Type class instantiate it.
 * Note this only works with a no argument constructor.
*/


public with sharing class ReflectivePizzaFactory {
    //test
    public Pizza createPizza(String typeOfPizza){
        Pizza__mdt pizza = Pizza__mdt.getInstance(typeOfPizza);
        Type t = Type.forName(pizza.Class_To_Instantiate__c);
        return (Pizza)t.newInstance();
    }
}