force-app/main/default/objects/Product_Catelog__c/Product_Catelog__c.object-meta.xml
<CustomObject>
    <description>Used to illustrate the Observer Pattern</description>
    <label>Product Catelog</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>Product Catelog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Catelogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Notification__c/Product_Notification__c.object-meta.xml
<CustomObject>
    <description>Used in Observer Pattern to notify users</description>
    <label>Product Notification</label>
    <nameField>
        <displayFormat>PN-{0000000}</displayFormat>
        <label>Product Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Notification__c/fields/Product_Catelog__c.field-meta.xml
<CustomField>
    <fullName>Product_Catelog__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Catelog</label>
    <referenceTo>Product_Catelog__c</referenceTo>
    <relationshipLabel>Product Notifications</relationshipLabel>
    <relationshipName>Product_Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Notification__c/fields/Subscribe__c.field-meta.xml
<CustomField>
    <fullName>Subscribe__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Subscribe</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Observer/ProductSubject.cls
/**
 * The publisher in the pub sub relationship
 */
public with sharing class ProductSubject implements ISubject {

    String id;

    public ProductSubject(String id) {
        this.id = id;
    }

    public void subscribe(Product_Notification__c observer) {
        observer.Product_Catelog__c = this.id;
        observer.Subscribe__c = true;

        insert observer;
    }

    public void unsubscribe(Product_Notification__c observer) {
        System.debug('Doing unsubscribe');
    }

    public void notifyObservers() {
        IObserver observer = new ProductObserver(this.id);
        observer.notify();
    }
}