force-app/main/default/objects/Product_Catelog__c/Product_Catelog__c.object-meta.xml
<CustomObject>
    <description>Used to illustrate the Observer Pattern</description>
    <label>Product Catelog</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>Product Catelog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Catelogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Notification__c/Product_Notification__c.object-meta.xml
<CustomObject>
    <description>Used in Observer Pattern to notify users</description>
    <label>Product Notification</label>
    <nameField>
        <displayFormat>PN-{0000000}</displayFormat>
        <label>Product Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Notification__c/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <label>Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Product_Notification__c/fields/Product_Catelog__c.field-meta.xml
<CustomField>
    <fullName>Product_Catelog__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Catelog</label>
    <referenceTo>Product_Catelog__c</referenceTo>
    <relationshipLabel>Product Notifications</relationshipLabel>
    <relationshipName>Product_Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Notification__c/fields/Subscribe__c.field-meta.xml
<CustomField>
    <fullName>Subscribe__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Subscribe</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Observer/ProductObserver.cls
/**
 * Created by Brooks Johnson on 3/26/2022.
 */

public with sharing class ProductObserver implements IObserver {
    String id;

    public ProductObserver(String id) {
        this.id = id;
    }

    public void notify() {
        List<Product_Notification__c> observers = [
                SELECT Id, Email_Address__c
                FROM Product_Notification__c
                WHERE Product_Catelog__c = :this.id
                AND Subscribe__c = TRUE
                WITH SECURITY_ENFORCED
        ];

        //mock email
        for (Product_Notification__c observer : observers) {
            System.debug('sending email to' + observer.Email_Address__c);
        }
    }

}