force-app/main/default/objects/Product_Catalog__c/Product_Catalog__c.object-meta.xml
<CustomObject>
    <description>Used to illustrate the Observer Pattern</description>
    <label>Product Catalog</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>Product Catelog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Catalogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Catalog__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <description>Used in observer pattern</description>
    <label>Product Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Notification__c/Product_Notification__c.object-meta.xml
<CustomObject>
    <description>Used in Observer Pattern to notify users</description>
    <label>Product Notification</label>
    <nameField>
        <displayFormat>PN-{0000000}</displayFormat>
        <label>Product Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Notification__c/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <label>Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/Observer/ObserverPatternController.cls
/**
 * Created by Brooks Johnson on 3/12/2022.
 */

public with sharing class ObserverPatternController {
  public static final String PRODUCT_QUERY =
          'SELECT Id, Name, Is_Available__c, Product_Name__c ' +
                  'FROM Product_Catalog__c ' +
                  'WITH SECURITY_ENFORCED LIMIT 1';

  @AuraEnabled(Cacheable=true)
  public static List<Product_Catalog__c> getProducts() {
    ISelector selector = SelectorFactory.getSelector();
    return (List<Product_Catalog__c>) selector.query(PRODUCT_QUERY);
  }

  @AuraEnabled
  public static void subscribeUser(String productId, String email) {
    Product_Notification__c notification = new Product_Notification__c(Email_Address__c = email);
    ISubject productSubject = new ProductSubject(productId);
    productSubject.subscribe(notification);
  }
}