force-app/main/default/objects/Chicago_Pizza__mdt/Chicago_Pizza__mdt.object-meta.xml
<CustomObject>
    <description>For a reflective factory</description>
    <label>Chicago Pizza</label>
    <pluralLabel>Chicago Pizza</pluralLabel>
</CustomObject>

force-app/main/default/objects/Chicago_Pizza__mdt/fields/Class_To_Instantiate__c.field-meta.xml
<CustomField>
    <fullName>Class_To_Instantiate__c</fullName>
    <description>The name of the  class to be instantiated by our Type class</description>
    <label>Class To Instantiate</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FactoryMethod/ChicagoPizzaStore.cls
public with sharing class ChicagoPizzaStore extends PizzaStore {

    /**
     * @description lets be fancy and do this one with a reflective factory method.
     * We are implementing an abstract method from our super class. It does not know or care
     * How we implement create pizza as long we have one.
     * @param pizzaType type of pizza to order
     *
     * @return Pizza
     */
    protected override Pizza createPizza(String pizzaType) {
        Chicago_Pizza__mdt pizza = Chicago_Pizza__mdt.getInstance(pizzaType);
        Type t = Type.forName(pizza.Class_To_Instantiate__c);
        return (Pizza) t.newInstance();
    }
}